print: True
digits: 4
iterations: 1_000
warmup: 1_000
replications: 20
seed: null
stepsize: 0.24
switch_limit: 3
segment_length: 2
db: experiments.db

bs_path: ~/bridgestan

model_path: stan
model_name: normal

init:
  warmup: 10_000
  iterations: 20_000
